.TH man 1 "27 Jun 2017" "0.1.0" "forten man page"
.SH NAME
forten \- evaluate forten code
.SH SYNOPSIS
forten <filename>
.SH DESCRIPTION
Forten is a preprocessor that has a very terse syntax. It was inspired by TeX and Puten.
.SH OPTIONS
The program does not take any options.
.SH BUGS
No known bugs.
.SH AUTHOR
Iikka Hauhio (fergusq@kaivos.org)
